### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by xhendev** [LiterallyFabian/MSPet.js#5]
Hello. The tool doesnt work anymore to me. Using vpn, using se server, seeing sweden language. It says petting (ids) but doesnt give s me fame and it doesnt count anymore to the daily quests.

**Comment by xhendev** [comment]
Oh i used the wrong userId. Maybe you can add a system to test if the userId is correct.

**Comment by LiterallyFabian** [comment]
Should be possible, depends on how MSP responds to requests. Will look into it within a few days

**Comment by xhendev** [comment]
Do you know which request to use to auto open the 4 daily "boxes/chests"?

**Comment by LiterallyFabian** [comment]
I actually looked into that + auto claim for the pet quest quickly earlier, but I wasn't able to get it working.

It's probably doable with a similar POST request, feel free to monitor the requests in the network tab and see if you could automate it.

**Comment by xhendev** [comment]
Im a noob haha. I can try it. Can you maybe explain why there are often 2 "requests" for one "name". one daily pickup put and one options methode

**Comment by LiterallyFabian** [comment]
I'm not too sure about it, but `options` is basically just checking with the server if the request is allowed or not if I've understood it correctly. I'm unsure if it's required, but since petting works without it I've been ignoring it. 

You could right click the requests, go to `Copy` -> `Copy as fetch` to get the fetch-code generated for you. That's what I've been doing, and it's why you can see my browser agent in the code.

**Comment by xhendev** [comment]
Oh i did that too. So i opened two daily pickups. Copied both 2 requests as fetch in a file. So i had two files. Then i put it in a text compare generator. And the result was that both text files were complity the same. Idk if you just can send 4 times a request that u opened a gift. I try it

**Comment by LiterallyFabian** [comment]
Yeah I've been checking diffs too, but for some reason when I tried to fake the gifts the only thing that happened was that I got unable to claim the gifts, even manually. I could click them in-game but nothing happened.

**Comment by xhendev** [comment]
Did you tried something with the "progress" request?

**Comment by LiterallyFabian** [comment]
I don't remember any names or URLs, but I tried the one that comes up when you open the gift

**Comment by xhendev** [comment]
When i copy as fetch it writes await before it. How do i make it work. Or do i only paste the real request and not answer of the request in the code?

**Comment by xhendev** [comment]
I think i have the problem too that i cant open the give now manually

**Comment by LiterallyFabian** [comment]
Yup that happened for me as well, but it will reset and work again after a day. 

Not too sure what you mean with pasting the answer, but all you need to paste is the auto-generated fetch, together with something to process the data, check out some examples; [https://www.npmjs.com/package/node-fetch](https://www.npmjs.com/package/node-fetch#json)

![image](https://user-images.githubusercontent.com/47401343/131221841-c6bd1c44-5377-418e-a797-d8f8b06187c5.png)
